// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// launch_pmmh_cpp
List launch_pmmh_cpp(List inputs, List modellist, List algoparameters);
RcppExport SEXP BatteryMCMC_launch_pmmh_cpp(SEXP inputsSEXP, SEXP modellistSEXP, SEXP algoparametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< List >::type modellist(modellistSEXP);
    Rcpp::traits::input_parameter< List >::type algoparameters(algoparametersSEXP);
    __result = Rcpp::wrap(launch_pmmh_cpp(inputs, modellist, algoparameters));
    return __result;
END_RCPP
}
