# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

launch_pmmh_cpp <- function(inputs, modellist, algoparameters) {
    .Call('BatteryMCMC_launch_pmmh_cpp', PACKAGE = 'BatteryMCMC', inputs, modellist, algoparameters)
}

